//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCVEntities2 : DbContext
    {
        public DbCVEntities2()
            : base("name=DbCVEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_admin> Tbl_admin { get; set; }
        public virtual DbSet<Tbl_egitimlerim> Tbl_egitimlerim { get; set; }
        public virtual DbSet<Tbl_hakkımda> Tbl_hakkımda { get; set; }
        public virtual DbSet<Tbl_hobilerim> Tbl_hobilerim { get; set; }
        public virtual DbSet<Tbl_iletişim> Tbl_iletişim { get; set; }
        public virtual DbSet<Tbl_serfikalarım> Tbl_serfikalarım { get; set; }
        public virtual DbSet<Tbl_yetenekler> Tbl_yetenekler { get; set; }
        public virtual DbSet<Tbldeneyimler> Tbldeneyimler { get; set; }
        public virtual DbSet<TblSosyalMedya> TblSosyalMedya { get; set; }
    }
}
